with-expecter: true
filename: "mock_{{.InterfaceName}}.go"
dir: "tests/mocks/{{.PackageName}}"
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}_mock"

packages:
  github.com/daemondxx/lks_back/internal/services/order:
    interfaces:
      LksAPI:

  github.com/daemondxx/lks_back/internal/services/collector:
    interfaces:
      UserDAO:
      NotificationService:
      OrderService:
