with-expecter: true
filename: "mock_{{.InterfaceName}}.go"
dir: "tests/mocks/{{.PackageName}}"
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}_mock"

packages:

  github.com/daemondxx/lks_back/internal/server/services/account:
    config:
      dir: "mocks/server/services/{{.PackageName}}"
    interfaces:
      TokenService:
      AccountDAO:

  github.com/daemondxx/lks_back/internal/server/services/credential:
    config:
      dir: "mocks/server/services/{{.PackageName}}"
    interfaces:
      AccountService:
      AuthChecker:
      CredentialDAO:

  github.com/daemondxx/lks_back/internal/server/controllers/account:
    config:
      dir: "mocks/server/controllers/{{.PackageName}}"
    interfaces:
      AccountService:

  github.com/daemondxx/lks_back/internal/server/middleware:
    config:
      dir: "mocks/server/{{.PackageName}}"
    interfaces:
      AccountService:
      TokenService:
