with-expecter: true
filename: "mock_{{.InterfaceName}}.go"
dir: "tests/mocks/{{.PackageName}}"
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}_mock"

packages:

  github.com/daemondxx/lks_back/internal/server/services/account:
    config:
      dir: "mocks/server/services/account"
    interfaces:
      TokenService:
      AccountDAO:

  github.com/daemondxx/lks_back/internal/server/services/credential:
    config:
      dir: "mocks/server/services/credential"
    interfaces:
      AccountService:
      AuthChecker:
      CredentialDAO:

  github.com/daemondxx/lks_back/internal/server/services/order:
    config:
      dir: "mocks/server/services/order"
    interfaces:
      OrderDAO:

  github.com/daemondxx/lks_back/internal/server/services/collector:
    config:
      dir: "mocks/server/services/collector"
    interfaces:
      OrderDAO:
      LKSApi:

  github.com/daemondxx/lks_back/internal/server/controllers/account:
    config:
      dir: "mocks/server/controllers/account"
    interfaces:
      AccountService:

  github.com/daemondxx/lks_back/internal/server/controllers/credential:
    config:
      dir: "mocks/server/controllers/{{.PackageName}}"
    interfaces:
      CredentialService:

  github.com/daemondxx/lks_back/internal/server/controllers/order:
    config:
      outpkg: "ctrl_{{.PackageName}}_mock"
      dir: "mocks/server/controllers/{{.PackageName}}"
    interfaces:
      OrderService:

  github.com/daemondxx/lks_back/internal/server/middleware:
    config:
      dir: "mocks/server/{{.PackageName}}"
    interfaces:
      AccountService:
      TokenService:
