version: '3'

tasks:
  dev-up:
    cmds:
      - docker compose -f docker-compose.local.yaml --env-file ./configs/.dev.local.env up

  dev-down:
    cmds:
      - docker compose down

  test-env-up:
    dotenv: ["./tests/.env"]
    cmds:
      - docker run --name tests-pg-db -p $PG_PORT:5432 -e POSTGRES_USER=$PG_USER -e POSTGRES_PASSWORD=$PG_PASSWORD -e POSTGRES_DB=$PG_DB -d postgres:13.3

  test-env-down:
    cmds:
      - docker stop tests-pg-db
      - docker rm tests-pg-db

  integration-test:
    cmds:
      - task: test-env-up
      - cmd: go test -run "^TestIntegration$"
      - defer: {task: test-env-down}

  gen-mock:
    cmds:
      - mockery