// Code generated by mockery v2.44.2. DO NOT EDIT.

package middleware_mock

import mock "github.com/stretchr/testify/mock"

// MockTokenService is an autogenerated mock type for the TokenService type
type MockTokenService struct {
	mock.Mock
}

type MockTokenService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenService) EXPECT() *MockTokenService_Expecter {
	return &MockTokenService_Expecter{mock: &_m.Mock}
}

// Parse provides a mock function with given fields: token
func (_m *MockTokenService) Parse(token string) (uint, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 uint
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (uint, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) uint); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Get(0).(uint)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenService_Parse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parse'
type MockTokenService_Parse_Call struct {
	*mock.Call
}

// Parse is a helper method to define mock.On call
//   - token string
func (_e *MockTokenService_Expecter) Parse(token interface{}) *MockTokenService_Parse_Call {
	return &MockTokenService_Parse_Call{Call: _e.mock.On("Parse", token)}
}

func (_c *MockTokenService_Parse_Call) Run(run func(token string)) *MockTokenService_Parse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTokenService_Parse_Call) Return(_a0 uint, _a1 error) *MockTokenService_Parse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenService_Parse_Call) RunAndReturn(run func(string) (uint, error)) *MockTokenService_Parse_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenService creates a new instance of MockTokenService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenService {
	mock := &MockTokenService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
