// Code generated by mockery v2.44.2. DO NOT EDIT.

package collector_mock

import (
	notifier "github.com/daemondxx/lks_back/internal/server/services/notifier"
	mock "github.com/stretchr/testify/mock"
)

// MockNotificationService is an autogenerated mock type for the NotificationService type
type MockNotificationService struct {
	mock.Mock
}

type MockNotificationService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotificationService) EXPECT() *MockNotificationService_Expecter {
	return &MockNotificationService_Expecter{mock: &_m.Mock}
}

// Send provides a mock function with given fields: msg
func (_m *MockNotificationService) Send(msg notifier.Message) error {
	ret := _m.Called(msg)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(notifier.Message) error); ok {
		r0 = rf(msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNotificationService_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockNotificationService_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - msg notifier.Message
func (_e *MockNotificationService_Expecter) Send(msg interface{}) *MockNotificationService_Send_Call {
	return &MockNotificationService_Send_Call{Call: _e.mock.On("Send", msg)}
}

func (_c *MockNotificationService_Send_Call) Run(run func(msg notifier.Message)) *MockNotificationService_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(notifier.Message))
	})
	return _c
}

func (_c *MockNotificationService_Send_Call) Return(_a0 error) *MockNotificationService_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotificationService_Send_Call) RunAndReturn(run func(notifier.Message) error) *MockNotificationService_Send_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNotificationService creates a new instance of MockNotificationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotificationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotificationService {
	mock := &MockNotificationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
