// Code generated by mockery v2.44.2. DO NOT EDIT.

package collector_mock

import (
	context "context"

	entity "github.com/daemondxx/lks_back/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockOrderService is an autogenerated mock type for the OrderService type
type MockOrderService struct {
	mock.Mock
}

type MockOrderService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderService) EXPECT() *MockOrderService_Expecter {
	return &MockOrderService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, cr, i
func (_m *MockOrderService) Create(ctx context.Context, cr *entity.Credential, i []entity.OrderItem) (*entity.Order, error) {
	ret := _m.Called(ctx, cr, i)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Credential, []entity.OrderItem) (*entity.Order, error)); ok {
		return rf(ctx, cr, i)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Credential, []entity.OrderItem) *entity.Order); ok {
		r0 = rf(ctx, cr, i)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.Credential, []entity.OrderItem) error); ok {
		r1 = rf(ctx, cr, i)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockOrderService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - cr *entity.Credential
//   - i []entity.OrderItem
func (_e *MockOrderService_Expecter) Create(ctx interface{}, cr interface{}, i interface{}) *MockOrderService_Create_Call {
	return &MockOrderService_Create_Call{Call: _e.mock.On("Create", ctx, cr, i)}
}

func (_c *MockOrderService_Create_Call) Run(run func(ctx context.Context, cr *entity.Credential, i []entity.OrderItem)) *MockOrderService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Credential), args[2].([]entity.OrderItem))
	})
	return _c
}

func (_c *MockOrderService_Create_Call) Return(_a0 *entity.Order, _a1 error) *MockOrderService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderService_Create_Call) RunAndReturn(run func(context.Context, *entity.Credential, []entity.OrderItem) (*entity.Order, error)) *MockOrderService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// PullNewOrder provides a mock function with given fields: ctx, cr
func (_m *MockOrderService) PullNewOrder(ctx context.Context, cr *entity.Credential) (*entity.Order, error) {
	ret := _m.Called(ctx, cr)

	if len(ret) == 0 {
		panic("no return value specified for PullNewOrder")
	}

	var r0 *entity.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Credential) (*entity.Order, error)); ok {
		return rf(ctx, cr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Credential) *entity.Order); ok {
		r0 = rf(ctx, cr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.Credential) error); ok {
		r1 = rf(ctx, cr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderService_PullNewOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PullNewOrder'
type MockOrderService_PullNewOrder_Call struct {
	*mock.Call
}

// PullNewOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - cr *entity.Credential
func (_e *MockOrderService_Expecter) PullNewOrder(ctx interface{}, cr interface{}) *MockOrderService_PullNewOrder_Call {
	return &MockOrderService_PullNewOrder_Call{Call: _e.mock.On("PullNewOrder", ctx, cr)}
}

func (_c *MockOrderService_PullNewOrder_Call) Run(run func(ctx context.Context, cr *entity.Credential)) *MockOrderService_PullNewOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Credential))
	})
	return _c
}

func (_c *MockOrderService_PullNewOrder_Call) Return(_a0 *entity.Order, _a1 error) *MockOrderService_PullNewOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderService_PullNewOrder_Call) RunAndReturn(run func(context.Context, *entity.Credential) (*entity.Order, error)) *MockOrderService_PullNewOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderService creates a new instance of MockOrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderService {
	mock := &MockOrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
