// Code generated by mockery v2.44.2. DO NOT EDIT.

package collector_mock

import (
	context "context"

	entity "github.com/daemondxx/lks_back/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockCredentialDAO is an autogenerated mock type for the CredentialDAO type
type MockCredentialDAO struct {
	mock.Mock
}

type MockCredentialDAO_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCredentialDAO) EXPECT() *MockCredentialDAO_Expecter {
	return &MockCredentialDAO_Expecter{mock: &_m.Mock}
}

// GetActualCredential provides a mock function with given fields: ctx
func (_m *MockCredentialDAO) GetActualCredential(ctx context.Context) ([]entity.Credential, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetActualCredential")
	}

	var r0 []entity.Credential
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entity.Credential, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entity.Credential); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Credential)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCredentialDAO_GetActualCredential_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActualCredential'
type MockCredentialDAO_GetActualCredential_Call struct {
	*mock.Call
}

// GetActualCredential is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCredentialDAO_Expecter) GetActualCredential(ctx interface{}) *MockCredentialDAO_GetActualCredential_Call {
	return &MockCredentialDAO_GetActualCredential_Call{Call: _e.mock.On("GetActualCredential", ctx)}
}

func (_c *MockCredentialDAO_GetActualCredential_Call) Run(run func(ctx context.Context)) *MockCredentialDAO_GetActualCredential_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockCredentialDAO_GetActualCredential_Call) Return(_a0 []entity.Credential, _a1 error) *MockCredentialDAO_GetActualCredential_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCredentialDAO_GetActualCredential_Call) RunAndReturn(run func(context.Context) ([]entity.Credential, error)) *MockCredentialDAO_GetActualCredential_Call {
	_c.Call.Return(run)
	return _c
}

// SetActiveStatus provides a mock function with given fields: ctx, cr
func (_m *MockCredentialDAO) SetActiveStatus(ctx context.Context, cr *entity.Credential) error {
	ret := _m.Called(ctx, cr)

	if len(ret) == 0 {
		panic("no return value specified for SetActiveStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Credential) error); ok {
		r0 = rf(ctx, cr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCredentialDAO_SetActiveStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetActiveStatus'
type MockCredentialDAO_SetActiveStatus_Call struct {
	*mock.Call
}

// SetActiveStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - cr *entity.Credential
func (_e *MockCredentialDAO_Expecter) SetActiveStatus(ctx interface{}, cr interface{}) *MockCredentialDAO_SetActiveStatus_Call {
	return &MockCredentialDAO_SetActiveStatus_Call{Call: _e.mock.On("SetActiveStatus", ctx, cr)}
}

func (_c *MockCredentialDAO_SetActiveStatus_Call) Run(run func(ctx context.Context, cr *entity.Credential)) *MockCredentialDAO_SetActiveStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Credential))
	})
	return _c
}

func (_c *MockCredentialDAO_SetActiveStatus_Call) Return(_a0 error) *MockCredentialDAO_SetActiveStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCredentialDAO_SetActiveStatus_Call) RunAndReturn(run func(context.Context, *entity.Credential) error) *MockCredentialDAO_SetActiveStatus_Call {
	_c.Call.Return(run)
	return _c
}

// SetInactiveStatus provides a mock function with given fields: ctx, cr
func (_m *MockCredentialDAO) SetInactiveStatus(ctx context.Context, cr *entity.Credential) error {
	ret := _m.Called(ctx, cr)

	if len(ret) == 0 {
		panic("no return value specified for SetInactiveStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Credential) error); ok {
		r0 = rf(ctx, cr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCredentialDAO_SetInactiveStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetInactiveStatus'
type MockCredentialDAO_SetInactiveStatus_Call struct {
	*mock.Call
}

// SetInactiveStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - cr *entity.Credential
func (_e *MockCredentialDAO_Expecter) SetInactiveStatus(ctx interface{}, cr interface{}) *MockCredentialDAO_SetInactiveStatus_Call {
	return &MockCredentialDAO_SetInactiveStatus_Call{Call: _e.mock.On("SetInactiveStatus", ctx, cr)}
}

func (_c *MockCredentialDAO_SetInactiveStatus_Call) Run(run func(ctx context.Context, cr *entity.Credential)) *MockCredentialDAO_SetInactiveStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Credential))
	})
	return _c
}

func (_c *MockCredentialDAO_SetInactiveStatus_Call) Return(_a0 error) *MockCredentialDAO_SetInactiveStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCredentialDAO_SetInactiveStatus_Call) RunAndReturn(run func(context.Context, *entity.Credential) error) *MockCredentialDAO_SetInactiveStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCredentialDAO creates a new instance of MockCredentialDAO. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCredentialDAO(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCredentialDAO {
	mock := &MockCredentialDAO{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
