// Code generated by mockery v2.44.2. DO NOT EDIT.

package service_account_mock

import (
	context "context"

	entity "github.com/daemondxx/lks_back/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockAccountDAO is an autogenerated mock type for the AccountDAO type
type MockAccountDAO struct {
	mock.Mock
}

type MockAccountDAO_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountDAO) EXPECT() *MockAccountDAO_Expecter {
	return &MockAccountDAO_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, a
func (_m *MockAccountDAO) Create(ctx context.Context, a *entity.Account) error {
	ret := _m.Called(ctx, a)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Account) error); ok {
		r0 = rf(ctx, a)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccountDAO_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAccountDAO_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - a *entity.Account
func (_e *MockAccountDAO_Expecter) Create(ctx interface{}, a interface{}) *MockAccountDAO_Create_Call {
	return &MockAccountDAO_Create_Call{Call: _e.mock.On("Create", ctx, a)}
}

func (_c *MockAccountDAO_Create_Call) Run(run func(ctx context.Context, a *entity.Account)) *MockAccountDAO_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Account))
	})
	return _c
}

func (_c *MockAccountDAO_Create_Call) Return(_a0 error) *MockAccountDAO_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountDAO_Create_Call) RunAndReturn(run func(context.Context, *entity.Account) error) *MockAccountDAO_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function with given fields: ctx, tgID
func (_m *MockAccountDAO) Find(ctx context.Context, tgID uint64) ([]entity.Account, error) {
	ret := _m.Called(ctx, tgID)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 []entity.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) ([]entity.Account, error)); ok {
		return rf(ctx, tgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) []entity.Account); ok {
		r0 = rf(ctx, tgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, tgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountDAO_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockAccountDAO_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - tgID uint64
func (_e *MockAccountDAO_Expecter) Find(ctx interface{}, tgID interface{}) *MockAccountDAO_Find_Call {
	return &MockAccountDAO_Find_Call{Call: _e.mock.On("Find", ctx, tgID)}
}

func (_c *MockAccountDAO_Find_Call) Run(run func(ctx context.Context, tgID uint64)) *MockAccountDAO_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockAccountDAO_Find_Call) Return(_a0 []entity.Account, _a1 error) *MockAccountDAO_Find_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountDAO_Find_Call) RunAndReturn(run func(context.Context, uint64) ([]entity.Account, error)) *MockAccountDAO_Find_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockAccountDAO) Get(ctx context.Context, id uint) (*entity.Account, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *entity.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*entity.Account, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *entity.Account); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountDAO_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockAccountDAO_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockAccountDAO_Expecter) Get(ctx interface{}, id interface{}) *MockAccountDAO_Get_Call {
	return &MockAccountDAO_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockAccountDAO_Get_Call) Run(run func(ctx context.Context, id uint)) *MockAccountDAO_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockAccountDAO_Get_Call) Return(_a0 *entity.Account, _a1 error) *MockAccountDAO_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountDAO_Get_Call) RunAndReturn(run func(context.Context, uint) (*entity.Account, error)) *MockAccountDAO_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, a
func (_m *MockAccountDAO) Save(ctx context.Context, a *entity.Account) error {
	ret := _m.Called(ctx, a)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Account) error); ok {
		r0 = rf(ctx, a)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccountDAO_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockAccountDAO_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - a *entity.Account
func (_e *MockAccountDAO_Expecter) Save(ctx interface{}, a interface{}) *MockAccountDAO_Save_Call {
	return &MockAccountDAO_Save_Call{Call: _e.mock.On("Save", ctx, a)}
}

func (_c *MockAccountDAO_Save_Call) Run(run func(ctx context.Context, a *entity.Account)) *MockAccountDAO_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Account))
	})
	return _c
}

func (_c *MockAccountDAO_Save_Call) Return(_a0 error) *MockAccountDAO_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountDAO_Save_Call) RunAndReturn(run func(context.Context, *entity.Account) error) *MockAccountDAO_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAccountDAO creates a new instance of MockAccountDAO. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountDAO(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountDAO {
	mock := &MockAccountDAO{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
