// Code generated by mockery v2.44.2. DO NOT EDIT.

package service_account_mock

import (
	entity "github.com/daemondxx/lks_back/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockTokenService is an autogenerated mock type for the TokenService type
type MockTokenService struct {
	mock.Mock
}

type MockTokenService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenService) EXPECT() *MockTokenService_Expecter {
	return &MockTokenService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: acc
func (_m *MockTokenService) Create(acc *entity.Account) string {
	ret := _m.Called(acc)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(*entity.Account) string); ok {
		r0 = rf(acc)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockTokenService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTokenService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - acc *entity.Account
func (_e *MockTokenService_Expecter) Create(acc interface{}) *MockTokenService_Create_Call {
	return &MockTokenService_Create_Call{Call: _e.mock.On("Create", acc)}
}

func (_c *MockTokenService_Create_Call) Run(run func(acc *entity.Account)) *MockTokenService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.Account))
	})
	return _c
}

func (_c *MockTokenService_Create_Call) Return(_a0 string) *MockTokenService_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenService_Create_Call) RunAndReturn(run func(*entity.Account) string) *MockTokenService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenService creates a new instance of MockTokenService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenService {
	mock := &MockTokenService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
