// Code generated by mockery v2.44.2. DO NOT EDIT.

package puller_mock

import (
	context "context"

	entity "github.com/daemondxx/lks_back/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockOrderDAO is an autogenerated mock type for the OrderDAO type
type MockOrderDAO struct {
	mock.Mock
}

type MockOrderDAO_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderDAO) EXPECT() *MockOrderDAO_Expecter {
	return &MockOrderDAO_Expecter{mock: &_m.Mock}
}

// FindLastOrders provides a mock function with given fields: ctx, cr, limit
func (_m *MockOrderDAO) FindLastOrders(ctx context.Context, cr *entity.Credential, limit int) ([]entity.Order, error) {
	ret := _m.Called(ctx, cr, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindLastOrders")
	}

	var r0 []entity.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Credential, int) ([]entity.Order, error)); ok {
		return rf(ctx, cr, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Credential, int) []entity.Order); ok {
		r0 = rf(ctx, cr, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.Credential, int) error); ok {
		r1 = rf(ctx, cr, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderDAO_FindLastOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindLastOrders'
type MockOrderDAO_FindLastOrders_Call struct {
	*mock.Call
}

// FindLastOrders is a helper method to define mock.On call
//   - ctx context.Context
//   - cr *entity.Credential
//   - limit int
func (_e *MockOrderDAO_Expecter) FindLastOrders(ctx interface{}, cr interface{}, limit interface{}) *MockOrderDAO_FindLastOrders_Call {
	return &MockOrderDAO_FindLastOrders_Call{Call: _e.mock.On("FindLastOrders", ctx, cr, limit)}
}

func (_c *MockOrderDAO_FindLastOrders_Call) Run(run func(ctx context.Context, cr *entity.Credential, limit int)) *MockOrderDAO_FindLastOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Credential), args[2].(int))
	})
	return _c
}

func (_c *MockOrderDAO_FindLastOrders_Call) Return(_a0 []entity.Order, _a1 error) *MockOrderDAO_FindLastOrders_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderDAO_FindLastOrders_Call) RunAndReturn(run func(context.Context, *entity.Credential, int) ([]entity.Order, error)) *MockOrderDAO_FindLastOrders_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, o
func (_m *MockOrderDAO) Save(ctx context.Context, o *entity.Order) error {
	ret := _m.Called(ctx, o)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Order) error); ok {
		r0 = rf(ctx, o)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrderDAO_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockOrderDAO_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - o *entity.Order
func (_e *MockOrderDAO_Expecter) Save(ctx interface{}, o interface{}) *MockOrderDAO_Save_Call {
	return &MockOrderDAO_Save_Call{Call: _e.mock.On("Save", ctx, o)}
}

func (_c *MockOrderDAO_Save_Call) Run(run func(ctx context.Context, o *entity.Order)) *MockOrderDAO_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Order))
	})
	return _c
}

func (_c *MockOrderDAO_Save_Call) Return(_a0 error) *MockOrderDAO_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderDAO_Save_Call) RunAndReturn(run func(context.Context, *entity.Order) error) *MockOrderDAO_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderDAO creates a new instance of MockOrderDAO. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderDAO(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderDAO {
	mock := &MockOrderDAO{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
