// Code generated by mockery v2.44.2. DO NOT EDIT.

package collector_mock

import (
	context "context"

	entity "github.com/daemondxx/lks_back/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockUserDAO is an autogenerated mock type for the UserDAO type
type MockUserDAO struct {
	mock.Mock
}

type MockUserDAO_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserDAO) EXPECT() *MockUserDAO_Expecter {
	return &MockUserDAO_Expecter{mock: &_m.Mock}
}

// Find provides a mock function with given fields: ctx, q
func (_m *MockUserDAO) Find(ctx context.Context, q entity.User) ([]entity.User, error) {
	ret := _m.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 []entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.User) ([]entity.User, error)); ok {
		return rf(ctx, q)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.User) []entity.User); ok {
		r0 = rf(ctx, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.User) error); ok {
		r1 = rf(ctx, q)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserDAO_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockUserDAO_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - q entity.User
func (_e *MockUserDAO_Expecter) Find(ctx interface{}, q interface{}) *MockUserDAO_Find_Call {
	return &MockUserDAO_Find_Call{Call: _e.mock.On("Find", ctx, q)}
}

func (_c *MockUserDAO_Find_Call) Run(run func(ctx context.Context, q entity.User)) *MockUserDAO_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.User))
	})
	return _c
}

func (_c *MockUserDAO_Find_Call) Return(_a0 []entity.User, _a1 error) *MockUserDAO_Find_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserDAO_Find_Call) RunAndReturn(run func(context.Context, entity.User) ([]entity.User, error)) *MockUserDAO_Find_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserDAO creates a new instance of MockUserDAO. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserDAO(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserDAO {
	mock := &MockUserDAO{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
