// Code generated by mockery v2.44.2. DO NOT EDIT.

package ctrl_account_mock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockAccountService is an autogenerated mock type for the AccountService type
type MockAccountService struct {
	mock.Mock
}

type MockAccountService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountService) EXPECT() *MockAccountService_Expecter {
	return &MockAccountService_Expecter{mock: &_m.Mock}
}

// CreateAccount provides a mock function with given fields: ctx, tgID
func (_m *MockAccountService) CreateAccount(ctx context.Context, tgID uint64) (string, error) {
	ret := _m.Called(ctx, tgID)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccount")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (string, error)); ok {
		return rf(ctx, tgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) string); ok {
		r0 = rf(ctx, tgID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, tgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountService_CreateAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAccount'
type MockAccountService_CreateAccount_Call struct {
	*mock.Call
}

// CreateAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - tgID uint64
func (_e *MockAccountService_Expecter) CreateAccount(ctx interface{}, tgID interface{}) *MockAccountService_CreateAccount_Call {
	return &MockAccountService_CreateAccount_Call{Call: _e.mock.On("CreateAccount", ctx, tgID)}
}

func (_c *MockAccountService_CreateAccount_Call) Run(run func(ctx context.Context, tgID uint64)) *MockAccountService_CreateAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockAccountService_CreateAccount_Call) Return(_a0 string, _a1 error) *MockAccountService_CreateAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountService_CreateAccount_Call) RunAndReturn(run func(context.Context, uint64) (string, error)) *MockAccountService_CreateAccount_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAccountService creates a new instance of MockAccountService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountService {
	mock := &MockAccountService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
