// Code generated by mockery v2.44.2. DO NOT EDIT.

package ctrl_order_mock

import (
	context "context"

	entity "github.com/daemondxx/lks_back/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockOrderService is an autogenerated mock type for the OrderService type
type MockOrderService struct {
	mock.Mock
}

type MockOrderService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderService) EXPECT() *MockOrderService_Expecter {
	return &MockOrderService_Expecter{mock: &_m.Mock}
}

// ConfirmOrder provides a mock function with given fields: ctx, acc, orderID
func (_m *MockOrderService) ConfirmOrder(ctx context.Context, acc entity.Account, orderID uint) error {
	ret := _m.Called(ctx, acc, orderID)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Account, uint) error); ok {
		r0 = rf(ctx, acc, orderID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrderService_ConfirmOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfirmOrder'
type MockOrderService_ConfirmOrder_Call struct {
	*mock.Call
}

// ConfirmOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - acc entity.Account
//   - orderID uint
func (_e *MockOrderService_Expecter) ConfirmOrder(ctx interface{}, acc interface{}, orderID interface{}) *MockOrderService_ConfirmOrder_Call {
	return &MockOrderService_ConfirmOrder_Call{Call: _e.mock.On("ConfirmOrder", ctx, acc, orderID)}
}

func (_c *MockOrderService_ConfirmOrder_Call) Run(run func(ctx context.Context, acc entity.Account, orderID uint)) *MockOrderService_ConfirmOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.Account), args[2].(uint))
	})
	return _c
}

func (_c *MockOrderService_ConfirmOrder_Call) Return(_a0 error) *MockOrderService_ConfirmOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderService_ConfirmOrder_Call) RunAndReturn(run func(context.Context, entity.Account, uint) error) *MockOrderService_ConfirmOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetActualOrders provides a mock function with given fields: ctx, acc
func (_m *MockOrderService) GetActualOrders(ctx context.Context, acc entity.Account) ([]entity.Order, error) {
	ret := _m.Called(ctx, acc)

	if len(ret) == 0 {
		panic("no return value specified for GetActualOrders")
	}

	var r0 []entity.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Account) ([]entity.Order, error)); ok {
		return rf(ctx, acc)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.Account) []entity.Order); ok {
		r0 = rf(ctx, acc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.Account) error); ok {
		r1 = rf(ctx, acc)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderService_GetActualOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActualOrders'
type MockOrderService_GetActualOrders_Call struct {
	*mock.Call
}

// GetActualOrders is a helper method to define mock.On call
//   - ctx context.Context
//   - acc entity.Account
func (_e *MockOrderService_Expecter) GetActualOrders(ctx interface{}, acc interface{}) *MockOrderService_GetActualOrders_Call {
	return &MockOrderService_GetActualOrders_Call{Call: _e.mock.On("GetActualOrders", ctx, acc)}
}

func (_c *MockOrderService_GetActualOrders_Call) Run(run func(ctx context.Context, acc entity.Account)) *MockOrderService_GetActualOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.Account))
	})
	return _c
}

func (_c *MockOrderService_GetActualOrders_Call) Return(_a0 []entity.Order, _a1 error) *MockOrderService_GetActualOrders_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderService_GetActualOrders_Call) RunAndReturn(run func(context.Context, entity.Account) ([]entity.Order, error)) *MockOrderService_GetActualOrders_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderService creates a new instance of MockOrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderService {
	mock := &MockOrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
