// Code generated by mockery v2.44.2. DO NOT EDIT.

package service_credential_mock

import (
	context "context"

	entity "github.com/daemondxx/lks_back/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockAccountService is an autogenerated mock type for the AccountService type
type MockAccountService struct {
	mock.Mock
}

type MockAccountService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountService) EXPECT() *MockAccountService_Expecter {
	return &MockAccountService_Expecter{mock: &_m.Mock}
}

// ConnectCredential provides a mock function with given fields: ctx, acc, cred
func (_m *MockAccountService) ConnectCredential(ctx context.Context, acc *entity.Account, cred *entity.Credential) error {
	ret := _m.Called(ctx, acc, cred)

	if len(ret) == 0 {
		panic("no return value specified for ConnectCredential")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Account, *entity.Credential) error); ok {
		r0 = rf(ctx, acc, cred)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccountService_ConnectCredential_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConnectCredential'
type MockAccountService_ConnectCredential_Call struct {
	*mock.Call
}

// ConnectCredential is a helper method to define mock.On call
//   - ctx context.Context
//   - acc *entity.Account
//   - cred *entity.Credential
func (_e *MockAccountService_Expecter) ConnectCredential(ctx interface{}, acc interface{}, cred interface{}) *MockAccountService_ConnectCredential_Call {
	return &MockAccountService_ConnectCredential_Call{Call: _e.mock.On("ConnectCredential", ctx, acc, cred)}
}

func (_c *MockAccountService_ConnectCredential_Call) Run(run func(ctx context.Context, acc *entity.Account, cred *entity.Credential)) *MockAccountService_ConnectCredential_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Account), args[2].(*entity.Credential))
	})
	return _c
}

func (_c *MockAccountService_ConnectCredential_Call) Return(_a0 error) *MockAccountService_ConnectCredential_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountService_ConnectCredential_Call) RunAndReturn(run func(context.Context, *entity.Account, *entity.Credential) error) *MockAccountService_ConnectCredential_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAccountService creates a new instance of MockAccountService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountService {
	mock := &MockAccountService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
