// Code generated by mockery v2.44.2. DO NOT EDIT.

package service_credential_mock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockAuthChecker is an autogenerated mock type for the AuthChecker type
type MockAuthChecker struct {
	mock.Mock
}

type MockAuthChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthChecker) EXPECT() *MockAuthChecker_Expecter {
	return &MockAuthChecker_Expecter{mock: &_m.Mock}
}

// Check provides a mock function with given fields: ctx, accLogin, accPass, lksLogin, lksPass
func (_m *MockAuthChecker) Check(ctx context.Context, accLogin string, accPass string, lksLogin string, lksPass string) error {
	ret := _m.Called(ctx, accLogin, accPass, lksLogin, lksPass)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = rf(ctx, accLogin, accPass, lksLogin, lksPass)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthChecker_Check_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Check'
type MockAuthChecker_Check_Call struct {
	*mock.Call
}

// Check is a helper method to define mock.On call
//   - ctx context.Context
//   - accLogin string
//   - accPass string
//   - lksLogin string
//   - lksPass string
func (_e *MockAuthChecker_Expecter) Check(ctx interface{}, accLogin interface{}, accPass interface{}, lksLogin interface{}, lksPass interface{}) *MockAuthChecker_Check_Call {
	return &MockAuthChecker_Check_Call{Call: _e.mock.On("Check", ctx, accLogin, accPass, lksLogin, lksPass)}
}

func (_c *MockAuthChecker_Check_Call) Run(run func(ctx context.Context, accLogin string, accPass string, lksLogin string, lksPass string)) *MockAuthChecker_Check_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockAuthChecker_Check_Call) Return(_a0 error) *MockAuthChecker_Check_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthChecker_Check_Call) RunAndReturn(run func(context.Context, string, string, string, string) error) *MockAuthChecker_Check_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthChecker creates a new instance of MockAuthChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthChecker {
	mock := &MockAuthChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
