// Code generated by mockery v2.44.2. DO NOT EDIT.

package ctrl_credential_mock

import (
	context "context"

	entity "github.com/daemondxx/lks_back/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockCredentialService is an autogenerated mock type for the CredentialService type
type MockCredentialService struct {
	mock.Mock
}

type MockCredentialService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCredentialService) EXPECT() *MockCredentialService_Expecter {
	return &MockCredentialService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, acc, lksLogin, lksPass, accLogin, accPass
func (_m *MockCredentialService) Create(ctx context.Context, acc *entity.Account, lksLogin string, lksPass string, accLogin string, accPass string) (*entity.Credential, error) {
	ret := _m.Called(ctx, acc, lksLogin, lksPass, accLogin, accPass)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.Credential
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Account, string, string, string, string) (*entity.Credential, error)); ok {
		return rf(ctx, acc, lksLogin, lksPass, accLogin, accPass)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Account, string, string, string, string) *entity.Credential); ok {
		r0 = rf(ctx, acc, lksLogin, lksPass, accLogin, accPass)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Credential)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.Account, string, string, string, string) error); ok {
		r1 = rf(ctx, acc, lksLogin, lksPass, accLogin, accPass)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCredentialService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCredentialService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - acc *entity.Account
//   - lksLogin string
//   - lksPass string
//   - accLogin string
//   - accPass string
func (_e *MockCredentialService_Expecter) Create(ctx interface{}, acc interface{}, lksLogin interface{}, lksPass interface{}, accLogin interface{}, accPass interface{}) *MockCredentialService_Create_Call {
	return &MockCredentialService_Create_Call{Call: _e.mock.On("Create", ctx, acc, lksLogin, lksPass, accLogin, accPass)}
}

func (_c *MockCredentialService_Create_Call) Run(run func(ctx context.Context, acc *entity.Account, lksLogin string, lksPass string, accLogin string, accPass string)) *MockCredentialService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Account), args[2].(string), args[3].(string), args[4].(string), args[5].(string))
	})
	return _c
}

func (_c *MockCredentialService_Create_Call) Return(_a0 *entity.Credential, _a1 error) *MockCredentialService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCredentialService_Create_Call) RunAndReturn(run func(context.Context, *entity.Account, string, string, string, string) (*entity.Credential, error)) *MockCredentialService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, accPass, lksPass
func (_m *MockCredentialService) Update(ctx context.Context, id uint, accPass string, lksPass string) error {
	ret := _m.Called(ctx, id, accPass, lksPass)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string, string) error); ok {
		r0 = rf(ctx, id, accPass, lksPass)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCredentialService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCredentialService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
//   - accPass string
//   - lksPass string
func (_e *MockCredentialService_Expecter) Update(ctx interface{}, id interface{}, accPass interface{}, lksPass interface{}) *MockCredentialService_Update_Call {
	return &MockCredentialService_Update_Call{Call: _e.mock.On("Update", ctx, id, accPass, lksPass)}
}

func (_c *MockCredentialService_Update_Call) Run(run func(ctx context.Context, id uint, accPass string, lksPass string)) *MockCredentialService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockCredentialService_Update_Call) Return(_a0 error) *MockCredentialService_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCredentialService_Update_Call) RunAndReturn(run func(context.Context, uint, string, string) error) *MockCredentialService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCredentialService creates a new instance of MockCredentialService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCredentialService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCredentialService {
	mock := &MockCredentialService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
