// Code generated by mockery v2.44.2. DO NOT EDIT.

package order_mock

import (
	context "context"

	entity "github.com/daemondxx/lks_back/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockOrderDAO is an autogenerated mock type for the OrderDAO type
type MockOrderDAO struct {
	mock.Mock
}

type MockOrderDAO_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderDAO) EXPECT() *MockOrderDAO_Expecter {
	return &MockOrderDAO_Expecter{mock: &_m.Mock}
}

// FindLastOrders provides a mock function with given fields: ctx, credID, limit
func (_m *MockOrderDAO) FindLastOrders(ctx context.Context, credID uint, limit int) ([]entity.Order, error) {
	ret := _m.Called(ctx, credID, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindLastOrders")
	}

	var r0 []entity.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, int) ([]entity.Order, error)); ok {
		return rf(ctx, credID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, int) []entity.Order); ok {
		r0 = rf(ctx, credID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, int) error); ok {
		r1 = rf(ctx, credID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderDAO_FindLastOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindLastOrders'
type MockOrderDAO_FindLastOrders_Call struct {
	*mock.Call
}

// FindLastOrders is a helper method to define mock.On call
//   - ctx context.Context
//   - credID uint
//   - limit int
func (_e *MockOrderDAO_Expecter) FindLastOrders(ctx interface{}, credID interface{}, limit interface{}) *MockOrderDAO_FindLastOrders_Call {
	return &MockOrderDAO_FindLastOrders_Call{Call: _e.mock.On("FindLastOrders", ctx, credID, limit)}
}

func (_c *MockOrderDAO_FindLastOrders_Call) Run(run func(ctx context.Context, credID uint, limit int)) *MockOrderDAO_FindLastOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(int))
	})
	return _c
}

func (_c *MockOrderDAO_FindLastOrders_Call) Return(_a0 []entity.Order, _a1 error) *MockOrderDAO_FindLastOrders_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderDAO_FindLastOrders_Call) RunAndReturn(run func(context.Context, uint, int) ([]entity.Order, error)) *MockOrderDAO_FindLastOrders_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderDAO creates a new instance of MockOrderDAO. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderDAO(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderDAO {
	mock := &MockOrderDAO{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
