// Code generated by mockery v2.44.2. DO NOT EDIT.

package service_order_mock

import (
	context "context"

	entity "github.com/daemondxx/lks_back/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockCredentialDAO is an autogenerated mock type for the CredentialDAO type
type MockCredentialDAO struct {
	mock.Mock
}

type MockCredentialDAO_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCredentialDAO) EXPECT() *MockCredentialDAO_Expecter {
	return &MockCredentialDAO_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockCredentialDAO) GetByID(ctx context.Context, id uint) (*entity.Credential, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Credential
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*entity.Credential, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *entity.Credential); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Credential)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCredentialDAO_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockCredentialDAO_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockCredentialDAO_Expecter) GetByID(ctx interface{}, id interface{}) *MockCredentialDAO_GetByID_Call {
	return &MockCredentialDAO_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockCredentialDAO_GetByID_Call) Run(run func(ctx context.Context, id uint)) *MockCredentialDAO_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockCredentialDAO_GetByID_Call) Return(_a0 *entity.Credential, _a1 error) *MockCredentialDAO_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCredentialDAO_GetByID_Call) RunAndReturn(run func(context.Context, uint) (*entity.Credential, error)) *MockCredentialDAO_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCredentialDAO creates a new instance of MockCredentialDAO. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCredentialDAO(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCredentialDAO {
	mock := &MockCredentialDAO{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
