// Code generated by mockery v2.44.2. DO NOT EDIT.

package service_order_mock

import (
	context "context"

	entity "github.com/daemondxx/lks_back/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockLKSApi is an autogenerated mock type for the LKSApi type
type MockLKSApi struct {
	mock.Mock
}

type MockLKSApi_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLKSApi) EXPECT() *MockLKSApi_Expecter {
	return &MockLKSApi_Expecter{mock: &_m.Mock}
}

// GetActualDuty provides a mock function with given fields: ctx, cr
func (_m *MockLKSApi) GetActualDuty(ctx context.Context, cr *entity.Credential) ([]entity.OrderItem, error) {
	ret := _m.Called(ctx, cr)

	if len(ret) == 0 {
		panic("no return value specified for GetActualDuty")
	}

	var r0 []entity.OrderItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Credential) ([]entity.OrderItem, error)); ok {
		return rf(ctx, cr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Credential) []entity.OrderItem); ok {
		r0 = rf(ctx, cr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.OrderItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.Credential) error); ok {
		r1 = rf(ctx, cr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLKSApi_GetActualDuty_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActualDuty'
type MockLKSApi_GetActualDuty_Call struct {
	*mock.Call
}

// GetActualDuty is a helper method to define mock.On call
//   - ctx context.Context
//   - cr *entity.Credential
func (_e *MockLKSApi_Expecter) GetActualDuty(ctx interface{}, cr interface{}) *MockLKSApi_GetActualDuty_Call {
	return &MockLKSApi_GetActualDuty_Call{Call: _e.mock.On("GetActualDuty", ctx, cr)}
}

func (_c *MockLKSApi_GetActualDuty_Call) Run(run func(ctx context.Context, cr *entity.Credential)) *MockLKSApi_GetActualDuty_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Credential))
	})
	return _c
}

func (_c *MockLKSApi_GetActualDuty_Call) Return(_a0 []entity.OrderItem, _a1 error) *MockLKSApi_GetActualDuty_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLKSApi_GetActualDuty_Call) RunAndReturn(run func(context.Context, *entity.Credential) ([]entity.OrderItem, error)) *MockLKSApi_GetActualDuty_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLKSApi creates a new instance of MockLKSApi. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLKSApi(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLKSApi {
	mock := &MockLKSApi{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
